# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-29 09:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=250)),
                ('user_type', models.CharField(choices=[('INV', 'Inventory'), ('SAL', 'Sales'), ('PRO', 'Procurement'), ('ACC', 'Accounting'), ('TEC', 'Technical'), ('ADM', 'Admin')], default='SAL', max_length=3)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
