# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-01 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='email',
            new_name='e_mail',
        ),
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.CharField(default='None', max_length=400),
            preserve_default=False,
        ),
    ]
