# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-01 14:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20171101_2224'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='e_mail',
            new_name='email_address',
        ),
    ]
