# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-01 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20171101_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='company_name',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
