# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-07 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20171102_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='user@digicom.ph', max_length=254),
        ),
    ]
