# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-08 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20171109_0342'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='confirm_password',
            field=models.CharField(default='', max_length=50),
        ),
    ]
