# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-08 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_profile_confirm_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='confirm_password',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
