# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-22 03:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20171120_1049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='is_accredited',
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('Inventory', 'Inventory'), ('Procurement', 'Procurement'), ('Accounting', 'Accounting'), ('Technical', 'Technical'), ('Admin', 'Admin'), ('Engineer', 'Engineer')], default='Procurement', max_length=50),
        ),
    ]
