# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-27 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20171122_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('Inventory', 'Inventory'), ('Procurement', 'Procurement'), ('Accounting', 'Accounting'), ('Technical', 'Technical'), ('Admin', 'Admin'), ('Engineer', 'Engineer'), ('SALES', 'Sales')], default='Procurement', max_length=50),
        ),
    ]
