# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-27 14:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20171127_2258'),
        ('products', '0008_auto_20171125_2205'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('is_done', models.BooleanField(default=False)),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Profile')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Supplier')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=0, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.PurchaseOrder')),
            ],
        ),
        migrations.RemoveField(
            model_name='requestedsupplies',
            name='product',
        ),
        migrations.RemoveField(
            model_name='requestedsupplies',
            name='supplier',
        ),
        migrations.DeleteModel(
            name='RequestedSupplies',
        ),
    ]
