# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-02 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_customer_is_accredited'),
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='responsible_department',
        ),
        migrations.AddField(
            model_name='schedule',
            name='involved_people',
            field=models.ManyToManyField(to='core.Profile'),
        ),
    ]
