# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-21 01:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_auto_20171121_0918'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='orderr',
            new_name='order',
        ),
    ]
