# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-06 10:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0012_auto_20171102_2036'),
        ('orders', '0014_delete_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderMaintenance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_contract_no', models.CharField(default='na', max_length=10)),
                ('date_created', models.DateField()),
                ('duration', models.DecimalField(decimal_places=2, max_digits=5)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orders.Order')),
            ],
        ),
        migrations.CreateModel(
            name='TroubleReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trouble_report_no', models.CharField(default='na', max_length=10)),
                ('date_requested', models.DateField()),
                ('date_created', models.DateField()),
                ('date_of_visit', models.DateField()),
                ('time_in', models.TimeField()),
                ('time_out', models.TimeField()),
                ('complaint', models.TextField(max_length=1500)),
                ('findings', models.TextField(max_length=1500)),
                ('engineer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Profile')),
            ],
        ),
    ]
