# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-04 02:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0012_auto_20171102_2036'),
        ('products', '0006_remove_product_reorder_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspector_report_no', models.CharField(default='N/A', max_length=15)),
                ('is_pending', models.BooleanField(default=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('payment_terms', models.CharField(choices=[('50-40-10', '50-40-10'), ('50-30-20', '50-30-20'), ('Full Payment', 'Full Payment')], default='0', max_length=40)),
                ('delivery_terms', models.CharField(default='N/A', max_length=1000)),
                ('warranty', models.DecimalField(decimal_places=0, default='0', max_digits=5)),
                ('completion', models.DecimalField(decimal_places=0, default='0', max_digits=5)),
                ('is_accredited', models.BooleanField(default=False)),
                ('has_project_requirements', models.BooleanField(default=False)),
                ('had_canvassed_suppliers', models.BooleanField(default=False)),
                ('has_contract', models.BooleanField(default=False)),
                ('has_retrieved_supplies', models.BooleanField(default=False)),
                ('is_delivered', models.BooleanField(default=False)),
                ('is_installed', models.BooleanField(default=False)),
                ('is_under_maintenance', models.BooleanField(default=False)),
                ('vendor_application', models.ImageField(default=None, null=True, upload_to='')),
                ('bir_certificate', models.ImageField(default=None, null=True, upload_to='')),
                ('dole_certification', models.ImageField(default=None, null=True, upload_to='')),
                ('org_chart', models.ImageField(default=None, null=True, upload_to='')),
                ('sec_registration_form', models.ImageField(default=None, null=True, upload_to='')),
                ('sss_certificate', models.ImageField(default=None, null=True, upload_to='')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=0, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
        ),
    ]
