# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-06 03:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_deliveryreceipt_officialreceipt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryreceipt',
            name='percentage',
        ),
    ]
