# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-06 03:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_remove_deliveryreceipt_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='invoice_no',
            field=models.CharField(default='na', max_length=10),
        ),
    ]
