# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-06 03:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_invoice_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='purchase_order_no',
            field=models.CharField(default='na', max_length=15),
        ),
        migrations.AlterField(
            model_name='order',
            name='inspector_report_no',
            field=models.CharField(default='na', max_length=15),
        ),
    ]
