# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-06 03:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20171106_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pull_out_slip_no',
            field=models.CharField(default='na', max_length=15),
        ),
    ]
