# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-06 05:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_order_pull_out_slip_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=15)),
                ('name2', models.CharField(max_length=15)),
                ('name3', models.CharField(max_length=15)),
                ('name4', models.CharField(max_length=15)),
                ('name5', models.BooleanField()),
                ('name6', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
