# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-06 05:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_person'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
