# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-07 15:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_delete_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='bir_certificate',
        ),
        migrations.RemoveField(
            model_name='order',
            name='dole_certification',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_accredited',
        ),
        migrations.RemoveField(
            model_name='order',
            name='org_chart',
        ),
        migrations.RemoveField(
            model_name='order',
            name='sec_registration_form',
        ),
        migrations.RemoveField(
            model_name='order',
            name='sss_certificate',
        ),
        migrations.RemoveField(
            model_name='order',
            name='vendor_application',
        ),
    ]
