# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-14 13:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_auto_20171107_2359'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectorReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspector_report_no', models.CharField(default='na', max_length=15)),
                ('duration', models.DecimalField(decimal_places=0, default='0', max_digits=5)),
                ('manpower', models.DecimalField(decimal_places=0, default='0', max_digits=5)),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='inspector_report_no',
        ),
        migrations.AddField(
            model_name='inspectorreport',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orders.Order'),
        ),
    ]
