# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-14 13:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_auto_20171114_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectorreport',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 14, 21, 20, 24, 245925)),
        ),
    ]
