# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-16 06:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_auto_20171114_2128'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=datetime.datetime.now)),
                ('payment_terms', models.CharField(choices=[('50-40-10', '50-40-10'), ('50-30-20', '50-30-20'), ('Full Payment', 'Full Payment')], default='0', max_length=40)),
                ('delivery_terms', models.CharField(default='N/A', max_length=1000)),
                ('warranty', models.DecimalField(decimal_places=0, default='0', max_digits=5)),
                ('completion', models.DecimalField(decimal_places=0, default='0', max_digits=5)),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='completion',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_terms',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_pending',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_terms',
        ),
        migrations.RemoveField(
            model_name='order',
            name='warranty',
        ),
        migrations.AddField(
            model_name='contract',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orders.Order'),
        ),
    ]
