# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-16 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_auto_20171116_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='consumables_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='contract',
            name='engineering_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='contract',
            name='installation_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
