# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-16 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_auto_20171116_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='completion',
            field=models.DecimalField(decimal_places=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='contract',
            name='consumables_fee',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='contract',
            name='delivery_terms',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='contract',
            name='engineering_fee',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='contract',
            name='installation_fee',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='contract',
            name='payment_terms',
            field=models.CharField(choices=[('50-40-10', '50-40-10'), ('50-30-20', '50-30-20'), ('Full Payment', 'Full Payment')], max_length=40),
        ),
        migrations.AlterField(
            model_name='contract',
            name='warranty',
            field=models.DecimalField(decimal_places=0, max_digits=5),
        ),
    ]
