# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-16 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_contract_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='number',
            field=models.CharField(max_length=15),
        ),
    ]
