# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-16 15:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_auto_20171116_2046'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingStatement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=15)),
                ('date_created', models.DateTimeField(default=datetime.datetime.now)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Order')),
            ],
        ),
        migrations.AlterField(
            model_name='contract',
            name='consumables_fee',
            field=models.DecimalField(decimal_places=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='contract',
            name='engineering_fee',
            field=models.DecimalField(decimal_places=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='contract',
            name='installation_fee',
            field=models.DecimalField(decimal_places=0, max_digits=5),
        ),
    ]
