# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-16 16:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0028_billingstatement_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingstatement',
            name='percentage',
        ),
    ]
