# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-16 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0029_remove_billingstatement_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingstatement',
            name='percentage',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=5),
            preserve_default=False,
        ),
    ]
