# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-16 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0030_billingstatement_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingstatement',
            name='item',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
