# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-17 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0032_auto_20171117_0109'),
    ]

    operations = [
        migrations.AddField(
            model_name='officialreceipt',
            name='number',
            field=models.CharField(default='', max_length=15),
        ),
    ]
