# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-17 08:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0034_auto_20171117_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officialreceipt',
            name='date_created',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
