# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-17 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0035_auto_20171117_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='form_of_payment',
            field=models.CharField(choices=[('Check', 'Check'), ('Cash', 'Cash')], default='Check', max_length=30),
        ),
    ]
