# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-20 05:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0037_order_has_scheduled_engineers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingstatement',
            name='percentage',
            field=models.DecimalField(decimal_places=0, help_text='In percent', max_digits=5),
        ),
    ]
