# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-20 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0038_auto_20171120_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingstatement',
            name='phase',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='deliveryreceipt',
            name='phase',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='officialreceipt',
            name='phase',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=5),
        ),
    ]
