# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-20 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0040_auto_20171120_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingstatement',
            name='phase',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='deliveryreceipt',
            name='phase',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='officialreceipt',
            name='phase',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=5),
        ),
    ]
