# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-20 10:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0041_auto_20171120_1849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingstatement',
            name='phase',
        ),
        migrations.RemoveField(
            model_name='deliveryreceipt',
            name='phase',
        ),
        migrations.RemoveField(
            model_name='officialreceipt',
            name='phase',
        ),
    ]
