# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-20 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0043_auto_20171120_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingstatement',
            name='phase',
            field=models.DecimalField(decimal_places=0, max_digits=2),
        ),
        migrations.AlterField(
            model_name='deliveryreceipt',
            name='phase',
            field=models.DecimalField(decimal_places=0, max_digits=2),
        ),
        migrations.AlterField(
            model_name='officialreceipt',
            name='phase',
            field=models.DecimalField(decimal_places=0, max_digits=2),
        ),
    ]
