# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-23 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0044_auto_20171120_1900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='invoice_no',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pull_out_slip_no',
        ),
        migrations.RemoveField(
            model_name='order',
            name='purchase_order_no',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default='Contract', max_length=100),
        ),
    ]
