# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-23 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0045_auto_20171123_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='Project Requirements', max_length=100),
        ),
    ]
