# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-26 05:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0052_auto_20171125_2229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingstatement',
            name='phase',
        ),
    ]
