# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-26 05:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0053_remove_billingstatement_phase'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='has_contract_done',
            field=models.BooleanField(default=False),
        ),
    ]
