# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-27 05:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20171122_1108'),
        ('orders', '0056_auto_20171126_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingstatement',
            name='generated_by',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='core.Profile'),
        ),
    ]
