# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-27 08:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0059_auto_20171127_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officialreceipt',
            name='generated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Profile'),
        ),
    ]
