# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-27 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0060_auto_20171127_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='has_scheduled_delivery',
            field=models.BooleanField(default=False),
        ),
    ]
