# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-27 15:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20171127_2258'),
        ('orders', '0061_order_has_scheduled_delivery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryreceipt',
            name='phase',
        ),
        migrations.AddField(
            model_name='deliveryreceipt',
            name='generated_by',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='core.Profile'),
        ),
    ]
