# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-27 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0063_auto_20171127_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryreceipt',
            name='number',
            field=models.CharField(default=0, max_length=15),
        ),
    ]
