# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-29 03:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0068_progressreport_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progressreport',
            name='title',
            field=models.CharField(max_length=256),
        ),
    ]
