# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-30 01:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0069_auto_20171129_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='has_finished_project',
            field=models.BooleanField(default=False),
        ),
    ]
