# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-30 01:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0070_order_has_finished_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='has_finished_advance',
            field=models.BooleanField(default=False),
        ),
    ]
