# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-30 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0071_order_has_finished_advance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progressreport',
            name='report_progress',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='progressreport',
            name='title',
            field=models.CharField(default='', max_length=256),
        ),
    ]
